# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  矫宗本的博客
subtitle: 千里之行，始于足下。
name: 矫宗本的博客
email: jiaozongben@gmail.com
description: 本站是矫宗本的技术分享博客。
keywords: Geek
encoding: "utf-8"
favicon: favicon.png

repository: james-xuande/james-xuande.github.io
github_url: https://github.com/james-xuande
url: https://james-xuande.github.io
enforce_ssl: james-xuande.github.io
github: [metadata]

#github: [3a84dcc736be38bf050fdaaed57dfa3a94427761]
## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
#menus:
#
#  -
#    href: /
#    label: Home
#
#  -
#    href: /archives.html
#    label: Archives
#    target: _self
#
#  -
#    href: /about.html
#    label: About
#    target: _self
 



# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  -
    href: /archives.html
    label: springboot
    target: _self

  -
    href: /api-test.html
    label: 接口测试
#    target: _self










# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 3 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: []
skill_web_keywords: []


